## 算術運算與填值

In [2]:
import pandas as pd
import numpy as np

In [5]:
df1 = pd.DataFrame(np.arange(12.).reshape(3,4), columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [7]:
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [9]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

* 直接相加 -> 為匹配的位置填滿NaN值

In [10]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

* 呼叫add方法及fill_value參數 -> 將陣列擴充，並將NaN值替換為fill_value參數

In [11]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

* 數學運算方法都有反向的方法，以r開頭

In [12]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [13]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

* 以不同的fill_value做索引填值

In [14]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## 算術運算方法
|方法|描述|
|:-:|:-:|
|add, radd|加法(+)|
|sub, rsub|減法(-)|
|div, rdiv|除法(/)|
|floordiv, rfloordiv|整除(//)|
|mul, rmul|乘法(\*)|
|pow, rpow|取冪(\*\*)|

## 在DataFrame和Series之間的運算

In [5]:
arr = np.arange(12.).reshape(3, 4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [6]:
arr[0]

array([0., 1., 2., 3.])

In [7]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [8]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3),
                     columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [10]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

* 在DataFrame及Series之間的算術運算 -> 預設行為是將Series的index和DataFrame的欄位做匹配，然後向下面的列作廣播

In [11]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

* 如果index在DataFrame的欄位找不到、或是在Series找不到 -> 產出的物件就以聯集重作索引

In [12]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [13]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

* 如果想做用列index做匹配，對欄做廣播 -> 使用方法做運算

In [15]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [16]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [17]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

* 傳入的軸編號是要進行匹配的軸，上述例子中是DataFrame的列index(axis='index'或axis=0)

## apply 和 applymap

In [2]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.298427 -1.472813 -0.739770
Ohio   -2.484620  1.732769 -0.304172
Texas   1.426389  1.255456  1.340806
Oregon -1.919050 -0.071001 -0.370908

In [3]:
np.abs(frame)

b         d         e
Utah    0.298427  1.472813  0.739770
Ohio    2.484620  1.732769  0.304172
Texas   1.426389  1.255456  1.340806
Oregon  1.919050  0.071001  0.370908

* 逐欄或逐列套用一個函式 -> apply方法 -> 預設逐欄

In [4]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    3.911009
d    3.205583
e    2.080576
dtype: float64

* 逐列計算

In [5]:
frame.apply(f, axis='columns')

Utah      1.174387
Ohio      4.217389
Texas     0.170933
Oregon    1.848049
dtype: float64

* 傳給apply的函式不一定要回傳常數值，它也可以回傳有多個值得Series

In [6]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min -2.484620 -1.472813 -0.739770
max  1.426389  1.732769  1.340806

* 也可以使用Python元素級別 -> applymap方法 -> 應用在每一個元素上

In [10]:
format = lambda x: F"{x:.2f}"
frame.applymap(format)

b      d      e
Utah    -0.30  -1.47  -0.74
Ohio    -2.48   1.73  -0.30
Texas    1.43   1.26   1.34
Oregon  -1.92  -0.07  -0.37

* Series的map方法 -> 對Series在元素級別進行動作

In [11]:
frame['e'].map(format)

Utah      -0.74
Ohio      -0.30
Texas      1.34
Oregon    -0.37
Name: e, dtype: object

## 排序和排名


* sort_index方法 -> 可以依欄或列index照字典序排序，並回傳新建立好的物件

In [12]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [13]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

* DataFrame -> 可以指定特定軸排序

In [14]:
frame = pd.DataFrame(np.arange(8).reshape(2, 4), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [15]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [16]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

* 預設是遞增排序，遞減排序 -> ascending=False

In [18]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

* 要對Series排序 -> sort_values()方法

In [19]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [20]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

* 缺失值會被擺在Series的最後面

In [21]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [22]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

* 在排序DataFrame中，可以指定一或多個欄的資料當作排序鍵值

In [23]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [24]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

* 要以多欄進行排序 -> 傳入欄名稱list

In [26]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

* **排名** 是將依個陣列中的有效資料從1開始排名次(由小到大)，使用Series或DataFrame的rank方法
* 遇到一樣大的值時，會採用他們的平均名次作為該組所有值的排名

In [27]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [28]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [29]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

* 指定降冪排序

In [31]:
obj.rank(ascending=False, method='max')  # method='max'指定平手時使用最大排名

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

* DataFrame可以分別對列或行進行排名

In [32]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [33]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 排名平手時的處理
|方法|描述|
|:-:|:-:|
|'average'|預設，為平手的值指定平均排名|
|'min'|為平手的值使用最小排名|
|'max'|為平手的值使用最大排名|
|'first'|看到平手的值，以出現次序排名|
|'dense'|同method='min'，排名名次永遠只依序+1，不會因為平手而增加跳過某個名次|

## 軸index有重複標籤

In [34]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

* 使用is_unique屬性可以告訴我們標籤是否有重複

In [35]:
obj.index.is_unique

False

* 標籤有重複進行索引 -> 回傳Series
* 標籤無重複進行索引 -> 回傳單一值

In [36]:
obj['a']

a    0
a    1
dtype: int64

In [37]:
obj['c']

4

In [38]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -1.150079  1.033309  1.867958
a -0.032596 -0.466903  0.754389
b -0.123031  0.024380  1.487343
b -1.997248  0.746821  0.324895

In [39]:
df.loc['b']

0         1         2
b -0.123031  0.024380  1.487343
b -1.997248  0.746821  0.324895

## 匯總和計算描述性統計量

* pandas物件配有一套常用的數學和統計方法，大多數屬於**歸納和匯總統計值(reduction or summary statistics)**，用來對Series或從DataFrame的列或欄所成的Series中取得單一結果值(e.g. 加總或平均數)
* 與numpy相比，內建了對缺失值的處理方法

In [3]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [4]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [5]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

* 除非整個切片(整列或整欄)都是NA，否則NA會被排除，可使用skipna參數來改變

In [6]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

## 歸納方法的選項
|方法|描述|
|:-:|:-:|
|axis|指定目標軸，0是DataFrame的列，1是欄|
|skipna|排除缺失值，預設是True|
|level|如果該軸使用階層式index(MultiIndex)的話，指定level進行歸納|

* idxmin -> 回傳最小值的index位置
* idxmax -> 回傳最大值的index位置

In [7]:
df.idxmax()

one    b
two    d
dtype: object

* 累加 -> cumsum()

In [8]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

* describe -> 產生多種統計值

In [9]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

* 若資料不是數值的話，descrie會產生另一種匯總統計

In [10]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [11]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## 描述和匯總統計值
|方法|描述|
|:-:|:-:|
|count|非NA值的總數|
|describe|為Series或每個DataFrame的欄位計算一匯總資料值|
|min, max|計算最小與最大值|
|argmin, argmax|計算最小與最大值的index位置(整數)|
|idxmin, idxmax|計算最小與最大值的index位置(標籤)|
|quantile|計算樣本從0到1的百分比排名|
|sum|值的加總|
|mean|值的平均|
|median|算術中位數(50%百分位數)|
|mad|平均值的絕對偏差|
|prod|所有值的乘積|
|var|樣本差異|
|std|樣本標準差|
|skew|值的樣本偏態(第三動差)|
|kurt|值的樣本峰態(第三動差)|
|cumsum|累加|
|cumin, cumax|重複前面最小值會最大值|
|cumprod|累乘|
|diff|計算和前值的算術差值|
|pct_change|計算值的百分比變化|

## 相關係數和共變異數

In [13]:
!pip install pandas-datareader

In [14]:
import pandas_datareader.data as web

In [15]:
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2016-08-05   26.912500   26.545000   26.567499   26.870001  162213600.0   
 2016-08-08   27.092501   26.790001   26.879999   27.092501  112148800.0   
 2016-08-09   27.235001   27.002501   27.057501   27.202499  105260800.0   
 2016-08-10   27.225000   26.940001   27.177500   27.000000   96034000.0   
 2016-08-11   27.232500   26.962500   27.129999   26.982500  109938000.0   
 ...                ...         ...         ...         ...          ...   
 2021-07-30  146.330002  144.110001  144.380005  145.860001   70382000.0   
 2021-08-02  146.949997  145.250000  146.360001  145.520004   62880000.0   
 2021-08-03  148.039993  145.179993  145.809998  147.360001   64660800.0   
 2021-08-04  147.789993  146.279999  147.270004  146.949997   56319800.0   
 2021-08-05  147.179993  146.169998  146.979996  147.041107   10097421.0   
 
  

In [16]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
price.head()

AAPL         IBM       MSFT        GOOG
Date                                                    
2016-08-05  25.237530  130.914124  53.396114  782.219971
2016-08-08  25.446508  130.865692  53.488247  781.760010
2016-08-09  25.549829  130.647629  53.617218  784.260010
2016-08-10  25.359632  130.897995  53.451401  784.679993
2016-08-11  25.343191  132.069031  53.709351  784.849976

In [28]:
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})
volume

AAPL        IBM        MSFT     GOOG
Date                                                   
2016-08-05  162213600.0  3812400.0  29335200.0  1801200
2016-08-08  112148800.0  3039300.0  19473500.0  1107900
2016-08-09  105260800.0  2737500.0  16920700.0  1318900
2016-08-10   96034000.0  2466700.0  15756900.0   786400
2016-08-11  109938000.0  8768600.0  18162300.0   975100
...                 ...        ...         ...      ...
2021-07-30   70382000.0  3534600.0  20940900.0  1196600
2021-08-02   62880000.0  2929500.0  16267400.0  1007000
2021-08-03   64660800.0  4083900.0  17863200.0   952600
2021-08-04   56319800.0  2829000.0  16184200.0   826000
2021-08-05   10097421.0   347953.0   2027503.0    86498

[1259 rows x 4 columns]

* 計算價格的百分比變化

In [20]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-07-30  0.001511 -0.006834 -0.005550 -0.009664
2021-08-02 -0.002331  0.003263 -0.000316  0.005683
2021-08-03  0.012644  0.018739  0.008075  0.002136
2021-08-04 -0.002782 -0.009093 -0.002124 -0.001845
2021-08-05  0.000620 -0.001436  0.004677 -0.000210

* Series中:
    * corr方法 -> 相關係數，計算兩個Series中重疊、非NA、按索引對齊的相關性
    * cov方法 -> 共變異數

In [21]:
returns['MSFT'].corr(returns['IBM'])

0.5177240179258893

In [22]:
returns['MSFT'].cov(returns['IBM'])

0.00014522545384713638

* 當名稱為Python合法名稱時，可使用更精簡的語法

In [23]:
returns.MSFT.corr(returns.IBM)

0.5177240179258893

* DataFrame:
    * corr、cov -> 回傳DataFrame的相關係數和共變異數矩陣

In [24]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.440883  0.735506  0.661954
IBM   0.440883  1.000000  0.517724  0.484528
MSFT  0.735506  0.517724  1.000000  0.775999
GOOG  0.661954  0.484528  0.775999  1.000000

In [25]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000137  0.000240  0.000211
IBM   0.000137  0.000268  0.000145  0.000133
MSFT  0.000240  0.000145  0.000294  0.000224
GOOG  0.000211  0.000133  0.000224  0.000282

* 使用DataFrame的corrwith方法 -> 可計算DataFrame裡面的欄或列跟其他Series或DataFrame之間的變異係數
* 將一個Series傳入，結果會回傳一個Series，其值為傳入的Series與每欄計算的結果

In [26]:
returns.corrwith(returns.IBM)

AAPL    0.440883
IBM     1.000000
MSFT    0.517724
GOOG    0.484528
dtype: float64

* 如果是傳入DataFrame的話，就會對名稱相同的欄進行變異係數值運算
* e.g. 股價百分比和成交量的變異係數

In [29]:
returns.corrwith(volume)

AAPL   -0.063177
IBM    -0.101979
MSFT   -0.056310
GOOG   -0.117979
dtype: float64

* 若傳入axis='columns'的話，會改為逐列計算
* 以上所有情況，在作變異係數計算前，資料點都會先以標籤對齊

In [30]:
returns.corrwith(volume, axis='columns')

Date
2016-08-05         NaN
2016-08-08    0.995242
2016-08-09    0.570102
2016-08-10   -0.923335
2016-08-11   -0.538176
                ...   
2021-07-30    0.976783
2021-08-02   -0.860431
2021-08-03    0.209175
2021-08-04    0.313097
2021-08-05    0.100352
Length: 1259, dtype: float64