## 算術運算與填值

In [1]:
import pandas as pd
import numpy as np

In [5]:
df1 = pd.DataFrame(np.arange(12.).reshape(3,4), columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [7]:
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [9]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

* 直接相加 -> 為匹配的位置填滿NaN值

In [10]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

* 呼叫add方法及fill_value參數 -> 將陣列擴充，並將NaN值替換為fill_value參數

In [11]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

* 數學運算方法都有反向的方法，以r開頭

In [12]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [13]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

* 以不同的fill_value做索引填值

In [14]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## 算術運算方法
|方法|描述|
|:-:|:-:|
|add, radd|加法(+)|
|sub, rsub|減法(-)|
|div, rdiv|除法(/)|
|floordiv, rfloordiv|整除(//)|
|mul, rmul|乘法(\*)|
|pow, rpow|取冪(\*\*)|

## 在DataFrame和Series之間的運算

In [5]:
arr = np.arange(12.).reshape(3, 4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [6]:
arr[0]

array([0., 1., 2., 3.])

In [7]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [8]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3),
                     columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [10]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

* 在DataFrame及Series之間的算術運算 -> 預設行為是將Series的index和DataFrame的欄位做匹配，然後向下面的列作廣播

In [11]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

* 如果index在DataFrame的欄位找不到、或是在Series找不到 -> 產出的物件就以聯集重作索引

In [12]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [13]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

* 如果想做用列index做匹配，對欄做廣播 -> 使用方法做運算

In [15]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [16]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [17]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

* 傳入的軸編號是要進行匹配的軸，上述例子中是DataFrame的列index(axis='index'或axis=0)

## apply 和 applymap

In [2]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.298427 -1.472813 -0.739770
Ohio   -2.484620  1.732769 -0.304172
Texas   1.426389  1.255456  1.340806
Oregon -1.919050 -0.071001 -0.370908

In [3]:
np.abs(frame)

b         d         e
Utah    0.298427  1.472813  0.739770
Ohio    2.484620  1.732769  0.304172
Texas   1.426389  1.255456  1.340806
Oregon  1.919050  0.071001  0.370908

* 逐欄或逐列套用一個函式 -> apply方法 -> 預設逐欄

In [4]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    3.911009
d    3.205583
e    2.080576
dtype: float64

* 逐列計算

In [5]:
frame.apply(f, axis='columns')

Utah      1.174387
Ohio      4.217389
Texas     0.170933
Oregon    1.848049
dtype: float64

* 傳給apply的函式不一定要回傳常數值，它也可以回傳有多個值得Series

In [6]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min -2.484620 -1.472813 -0.739770
max  1.426389  1.732769  1.340806

* 也可以使用Python元素級別 -> applymap方法 -> 應用在每一個元素上

In [10]:
format = lambda x: F"{x:.2f}"
frame.applymap(format)

b      d      e
Utah    -0.30  -1.47  -0.74
Ohio    -2.48   1.73  -0.30
Texas    1.43   1.26   1.34
Oregon  -1.92  -0.07  -0.37

* Series的map方法 -> 對Series在元素級別進行動作

In [11]:
frame['e'].map(format)

Utah      -0.74
Ohio      -0.30
Texas      1.34
Oregon    -0.37
Name: e, dtype: object

## 排序和排名


* sort_index方法 -> 可以依欄或列index照字典序排序，並回傳新建立好的物件

In [12]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [13]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

* DataFrame -> 可以指定特定軸排序

In [14]:
frame = pd.DataFrame(np.arange(8).reshape(2, 4), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [15]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [16]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

* 預設是遞增排序，遞減排序 -> ascending=False

In [18]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

* 要對Series排序 -> sort_values()方法

In [19]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [20]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

* 缺失值會被擺在Series的最後面

In [21]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [22]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

* 在排序DataFrame中，可以指定一或多個欄的資料當作排序鍵值

In [23]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [24]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

* 要以多欄進行排序 -> 傳入欄名稱list

In [26]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

* **排名** 是將依個陣列中的有效資料從1開始排名次(由小到大)，使用Series或DataFrame的rank方法
* 遇到一樣大的值時，會採用他們的平均名次作為該組所有值的排名

In [27]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [28]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [29]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

* 指定降冪排序

In [31]:
obj.rank(ascending=False, method='max')  # method='max'指定平手時使用最大排名

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

* DataFrame可以分別對列或行進行排名

In [32]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [33]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 排名平手時的處理
|方法|描述|
|:-:|:-:|
|'average'|預設，為平手的值指定平均排名|
|'min'|為平手的值使用最小排名|
|'max'|為平手的值使用最大排名|
|'first'|看到平手的值，以出現次序排名|
|'dense'|同method='min'，排名名次永遠只依序+1，不會因為平手而增加跳過某個名次|

## 軸index有重複標籤

In [34]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

* 使用is_unique屬性可以告訴我們標籤是否有重複

In [35]:
obj.index.is_unique

False

* 標籤有重複進行索引 -> 回傳Series
* 標籤無重複進行索引 -> 回傳單一值

In [36]:
obj['a']

a    0
a    1
dtype: int64

In [37]:
obj['c']

4

In [38]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -1.150079  1.033309  1.867958
a -0.032596 -0.466903  0.754389
b -0.123031  0.024380  1.487343
b -1.997248  0.746821  0.324895

In [39]:
df.loc['b']

0         1         2
b -0.123031  0.024380  1.487343
b -1.997248  0.746821  0.324895

## 匯總和計算描述性統計量

* pandas物件配有一套常用的數學和統計方法，大多數屬於**歸納和匯總統計值(reduction or summary statistics)**，用來對Series或從DataFrame的列或欄所成的Series中取得單一結果值(e.g. 加總或平均數)
* 與numpy相比，內建了對缺失值的處理方法

In [41]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [42]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [43]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

* 除非整個切片(整列或整欄)都是NA，否則NA會被排除，可使用skipna參數來改變

In [44]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

## 歸納方法的選項
|方法|描述|
|:-:|:-:|
|axis|指定目標軸，0是DataFrame的列，1是欄|
|skipna|排除缺失值，預設是True|
|level|如果該軸使用階層式index(MultiIndex)的話，指定level進行歸納|